### ISSUE TITLE
Clarification: event handlers

### ISSUE THREAD

**Issue by nicoandmee** [hindmost/reduxed-chrome-storage#11]
Thanks for creating this library, it's been beneficial for me as I'm working on an extension (not the original author) and attempting to make it compliant with Manifest v3 spec. I use `redux-saga` in my background script.

In one of my sagas, I have this:
```js
import { eventChannel } from 'redux-saga';
import {
  fork,
  put,
  takeLeading,
} from 'redux-saga/effects';

import {
  getTabId,
} from 'actions';

function* onMessage({ type, payload, _sender }) {
  // const { type, payload, sender } = action;
  if (type) {
    yield put({ type, payload, _sender });
  }
}

function* handleMessages() {
  const channel = yield eventChannel((emit) => {
    const listener = (action, _sender) => {
      emit({ ...action, _sender });
    };
    chrome.runtime.onMessage.addListener(listener);
    return () => chrome.runtime.onMessage.removeListener(listener);
  });

  yield takeLeading(channel, onMessage);
}

function handleGetTabId() {
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message.type === getTabId.type) {
      sendResponse({ tabId: _sender.tab.id });
    }
    sendResponse();
  });
}

export default function* appSaga() {
  // Grab global messages and pass them through. Different than connect
  //    channels actions.
  yield fork(handleMessages);
  yield fork(handleGetTabId);
}
```
Initially, I was unable to get `dispatch()` to work on the store within the ~~content script~~ popup. Previously it was working with v2. So I went from this:
```js
  useEffect(() => {
    dispatch(amSetLocation(JSON.parse(JSON.stringify(location))));
  }, [dispatch, location]);
```
To this:
```js
  useEffect(() => {
    chrome.runtime.sendMessage(amSetLocation(JSON.parse(JSON.stringify(location))));
  }, [location]);
```
Now it works.
Could that (the presence of event listeners) be the cause why `dispatch()` fails to synchronize the store? In other words- if you place an event handler after the first await occurrence as described in README, what are the consequences?

**Comment by hindmost** [comment]
> I was unable to get dispatch() to work on the store within the content script
> ..why dispatch() fails to synchronize the store?

It's unclear how exactly your store is created/connected. I only see `dispatch` call alone. With such info I can't say anything.

However I can certainly say that your `chrome.runtime.onMessage` calls above _**won't work**_. And this is unrelated to my library. Every Chrome API event listener must be registered at the top-level - this is a [requirement for service workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#event_listeners). Regarding the code above, you chose the wrong approach. Instead of spawning `chrome.runtime.onMessage` listeners, you have to create a custom function that will store listeners in an array. Then register _**single**_ ("global") `chrome.runtime.onMessage` listener where the stored listeners are to be called. And voila, you have your own subscriber function. See [this](https://github.com/hindmost/reduxed-chrome-storage/blob/master/src/WrappedStorage.ts#L51) for example.

**Comment by nicoandmee** [comment]
My store is setup like this in the background script:
```js
import { createStore, applyMiddleware } from '@reduxjs/toolkit';
import storeCreatorFactory from 'reduxed-chrome-storage';
import { stdChannel, runSaga } from 'redux-saga';
import { createLogger } from 'redux-logger';

import rootReducer from './rootReducer';
import rootSaga from './rootSaga';

const errorListener = (message, exceeded) => {
  console.error(message);
};

function setupSaga() {
  const channel = stdChannel();
  const sagaMiddleware = () => (next) => (action) => {
    const result = next(action);
    channel.put(action);
    return result;
  };

  return { channel, sagaMiddleware };
}

const { channel, sagaMiddleware } = setupSaga();
const middleware = [sagaMiddleware];

const logger = createLogger({
  diff: true,
  // collapsed: (getState, action) => action.type === 'MAIN_NETWORK_RESPONSE',
  predicate: (getState, action) => action.type !== 'MAIN_NETWORK_RESPONSE',
});
middleware.push(logger);

(async () => {
  const store = await storeCreatorFactory({ createStore, errorListener })(
    rootReducer,
    applyMiddleware(...middleware)
  );

  // Run sagas using custom channel to overcome async reduxed store problems
  runSaga(
    {
      channel,
      dispatch: store.dispatch,
      getState: () => store.getState(),
    },
    rootSaga
  );


  const tabs = await chrome.tabs.query({});
  await chrome.tabs.update(tabs[0].id, { url: 'chrome://extensions' });
})();
```
I created it in this way based on this issue https://github.com/hindmost/reduxed-chrome-storage/issues/6 where the OP also was using redux-store. What you're saying does make sense. But let's say I have created store in background as above, and then in my popup I have the following:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, configureStore, applyMiddleware, getDefaultMiddleware } from '@reduxjs/toolkit';
import storeCreatorFactory from 'reduxed-chrome-storage';

import './index.css';
import App from './features/App';

(async () => {
  const asyncStoreCreator = storeCreatorFactory({ createStore });
  const store = await asyncStoreCreator(state => state);

  const state = store.getState();
  console.log(state);

  await ReactDOM.render(
    <Provider store={store}>
      <App />
    </Provider>,
    document.getElementById('root'),
  );
})();
```
Note I have created in this fashion b/c in this case I am not using redux-saga so I don't need the workaround. Then within some component in the popup, I want to dispatch an action to the store on form submit like this:
```
const onFinish = payload => {
    // dispatch(loginRequest(payload));
    chrome.runtime.sendMessage(loginRequest(payload));
  };
```
Am I correct in understanding that the **correct** way to do this is the commented out line- action is dispatched to store and synced to storage, and so listeners in the background script should be triggered? The strange thing is that doesn't work- no indication that the store state has changed. The only way to get it to work was to send the action payload using `chrome.runtime.sendMessage()` - which is picked up by the first saga I posted and broadcast to the store.
It does appear though that according to docs this should not be possible b/c as you said listeners are not registered in the top level. Does it matter that everything is minified to a single file on build? 
Let me also pose another question- let's say in my content scripts at some point I need to communicate something to the background script/service worker. What's the right way to do this- can I have a listener in the background to handle that?

**Comment by hindmost** [comment]
> The strange thing is that doesn't work- no indication that the store state has changed.

I guess you want/expect `redux-logger` (set up in SW) to always show any state change made outside SW. But that won't work, at least not that way. AFAIU `redux-logger` register a state change listener via `store.subscribe`. The problem is that any `store` instance declared in SW is _**temporary**_, it doesn't live forever. This is due to [SW restrictions](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#events), again. So I don't recommend to use in SW top-level `store` instances along with `store.subscribe` as well as any 3rd-party libraries that depend on `store.subscribe`.
If you want to listen for state changes in SW, you can register a "global" listener via [`changeListener`](https://github.com/hindmost/reduxed-chrome-storage#state-change-listening-special-case---only-makes-sense-in-manifest-v3-service-workers) option. This most likely means that you can't use `redux-logger` in SW, unless it allows to change the method of subscription for state changes.
